Fix Spring exception in gwc-sqlite community module
Small contribution: change in applicationContext.xml
required after Spring upgrade to avoid bean initialization exception

org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.springframework.web.multipart.commons.CommonsMultipartResolver] for bean with name 'filterMultipartResolver' defined in URL [jar:file:..gs-gwc-sqlite-3.0-SNAPSHOT.jar!/applicationContext.xml]